### ISSUE TITLE
Migrate wiki into the sphinx

### ISSUE THREAD

**Issue by mmdbalkhi** [parchlinux/parchwiki#2]
For some reason, we need to **internationalize** our wiki. It seems like a good choice to use [Sphinx](https://sphinx-doc.org), which offers a variety of themes and add-ons to improve our wiki. We would appreciate any other suggestions for ParchWiki as well.

**Comment by behdanisohrab** [comment]
@mmdbalkhi good idea
the sphinx is ok to use
also it should be multilingual
we could use Hugo as well but its not optimized for rtl.


sohrab
